name: reproductor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  on_audio_query: 2.9.0
  just_audio: ^0.9.40
  permission_handler: ^11.3.0
  audio_video_progress_bar: ^2.0.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

